#ifndef GLOBALS_H_INCLUDED
#define GLOBALS_H_INCLUDED

const int SCREEN_WIDTH = 1024;
const int SCREEN_HEIGHT = 768;
const int CELL_SIZE = 64;
const int GRID_WIDTH = SCREEN_WIDTH / CELL_SIZE;
const int GRID_HEIGHT = SCREEN_HEIGHT / CELL_SIZE;
const int FPS = 30;

#endif // GLOBALS_H_INCLUDED
